import { CollectionRoute, SmartBin, UserProfile, WastePrediction, WasteReport } from '@/types/smartwaste';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-admin-1',
    full_name: 'Rajesh Kumar (Panchayat Admin)',
    email: 'admin@smartwaste.gov.in',
    phone: '+91 98765 43210',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'user-driver-1',
    full_name: 'Ramesh Patel (Driver #1)',
    email: 'ramesh.p@smartwaste.gov.in',
    phone: '+91 98123 45678',
    role: 'driver',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'user-citizen-1',
    full_name: 'Ananya Sharma (Citizen)',
    email: 'ananya@gmail.com',
    phone: '+91 99887 76655',
    role: 'citizen',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
  },
];

export const INITIAL_REPORTS: WasteReport[] = [
  {
    id: 'rep-001',
    reporter_id: 'user-citizen-1',
    location_name: 'Narasipuram Main Road',
    latitude: 11.0003,
    longitude: 76.7725,
    waste_category: 'overflowing_bin',
    category: 'overflowing_bin',
    description: 'Overflowing plastic packaging and commercial waste near Narasipuram Main Road bazaar during afternoon hours.',
    photo_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=800',
    image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&q=80&w=800',
    location_type: 'commercial',
    estimated_volume: 'massive',
    severity: 'CRITICAL',
    priority_score: 92,
    priority_level: 'CRITICAL',
    status: 'Submitted',
    upvotes_count: 8,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rep-002',
    reporter_id: 'user-citizen-1',
    location_name: 'Vellaimalaipattinam Residential Area',
    latitude: 10.9980,
    longitude: 76.7650,
    waste_category: 'hazardous',
    category: 'hazardous',
    description: 'Improper disposal of medical packaging and waste bins near Vellaimalaipattinam clinic entrance.',
    photo_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&q=80&w=800',
    image_url: 'https://images.unsplash.com/photo-1605600659908-0ef719419d41?auto=format&fit=crop&q=80&w=800',
    location_type: 'residential',
    estimated_volume: 'medium',
    severity: 'CRITICAL',
    priority_score: 84,
    priority_level: 'CRITICAL',
    status: 'Assigned',
    upvotes_count: 4,
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rep-003',
    reporter_id: 'user-citizen-1',
    location_name: 'Ikkaraibooluvampatti Community Area',
    latitude: 11.0085,
    longitude: 76.7620,
    waste_category: 'organic',
    category: 'organic',
    description: 'Decaying vegetable scraps and organic waste accumulated near Ikkaraibooluvampatti community center.',
    photo_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    location_type: 'market',
    estimated_volume: 'large',
    severity: 'HIGH',
    priority_score: 68,
    priority_level: 'HIGH',
    status: 'In Progress',
    upvotes_count: 3,
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rep-004',
    reporter_id: 'user-citizen-1',
    location_name: 'Devarayapuram Main Road',
    latitude: 10.9880,
    longitude: 76.7820,
    waste_category: 'recyclable',
    category: 'recyclable',
    description: 'Discarded beverage bottles and cardboard cartons near Devarayapuram bus stand.',
    photo_url: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
    image_url: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&q=80&w=800',
    location_type: 'transit_hub',
    estimated_volume: 'small',
    severity: 'MEDIUM',
    priority_score: 42,
    priority_level: 'MEDIUM',
    status: 'Resolved',
    upvotes_count: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_SMART_BINS: SmartBin[] = [
  {
    id: 'bin-101',
    bin_code: 'SB-ESP32-01',
    location_name: 'Narasipuram Main Road Bin',
    latitude: 11.0003,
    longitude: 76.7725,
    location_type: 'commercial',
    capacity_liters: 240,
    fill_percentage: 95,
    weight_kg: 42.5,
    battery_level: 88,
    is_online: true,
    last_ping: new Date().toISOString(),
    priority_score: 95,
    priority_level: 'CRITICAL',
    status: 'needs_collection',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bin-102',
    bin_code: 'SB-ESP32-02',
    location_name: 'Vellaimalaipattinam Residential Bin',
    latitude: 10.9980,
    longitude: 76.7650,
    location_type: 'residential',
    capacity_liters: 240,
    fill_percentage: 78,
    weight_kg: 34.0,
    battery_level: 92,
    is_online: true,
    last_ping: new Date().toISOString(),
    priority_score: 78,
    priority_level: 'HIGH',
    status: 'needs_collection',
    created_at: new Date().toISOString(),
  },
  {
    id: 'bin-103',
    bin_code: 'SB-ESP32-03',
    location_name: 'Ikkaraibooluvampatti Community Bin',
    latitude: 11.0085,
    longitude: 76.7620,
    location_type: 'residential',
    capacity_liters: 120,
    fill_percentage: 35,
    weight_kg: 12.0,
    battery_level: 64,
    is_online: true,
    last_ping: new Date().toISOString(),
    priority_score: 35,
    priority_level: 'LOW',
    status: 'active',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_ROUTES: CollectionRoute[] = [
  {
    id: 'route-901',
    title: 'Narasipuram Area Priority Sweep #1',
    driver_id: 'user-driver-1',
    driver_name: 'Ramesh Patel (Driver #1)',
    vehicle_number: 'TN-37-EV-2024 (Electric Tipper)',
    total_distance_km: 7.2,
    estimated_duration_mins: 40,
    status: 'assigned',
    created_at: new Date().toISOString(),
    stops: [
      {
        id: 'stop-1',
        route_id: 'route-901',
        report_id: 'rep-001',
        stop_order: 1,
        location_name: 'Narasipuram Main Road',
        latitude: 11.0003,
        longitude: 76.7725,
        priority_level: 'CRITICAL',
        status: 'pending',
        waste_category: 'overflowing_bin',
      },
      {
        id: 'stop-2',
        route_id: 'route-901',
        bin_id: 'bin-101',
        stop_order: 2,
        location_name: 'Vellaimalaipattinam Residential Area',
        latitude: 10.9980,
        longitude: 76.7650,
        priority_level: 'CRITICAL',
        status: 'pending',
        waste_category: 'hazardous',
      },
      {
        id: 'stop-3',
        route_id: 'route-901',
        report_id: 'rep-002',
        stop_order: 3,
        location_name: 'Ikkaraibooluvampatti Community Area',
        latitude: 11.0085,
        longitude: 76.7620,
        priority_level: 'CRITICAL',
        status: 'pending',
        waste_category: 'organic',
      },
      {
        id: 'stop-4',
        route_id: 'route-901',
        report_id: 'rep-003',
        stop_order: 4,
        location_name: 'Devarayapuram Main Road',
        latitude: 10.9880,
        longitude: 76.7820,
        priority_level: 'HIGH',
        status: 'pending',
        waste_category: 'recyclable',
      },
    ],
  },
];

export const INITIAL_PREDICTIONS: WastePrediction[] = [
  {
    id: 'pred-1',
    zone_name: 'Narasipuram Main Road',
    latitude: 11.0003,
    longitude: 76.7725,
    forecast_date: 'Tomorrow',
    predicted_volume_kg: 480,
    hotspot_risk: 'CRITICAL',
    confidence_score: 91,
  },
  {
    id: 'pred-2',
    zone_name: 'Devarayapuram Main Road',
    latitude: 10.9880,
    longitude: 76.7820,
    forecast_date: 'Tomorrow',
    predicted_volume_kg: 320,
    hotspot_risk: 'HIGH',
    confidence_score: 87,
  },
  {
    id: 'pred-3',
    zone_name: 'Thennamanallur Residential Area',
    latitude: 10.9780,
    longitude: 76.7920,
    forecast_date: 'Tomorrow',
    predicted_volume_kg: 140,
    hotspot_risk: 'LOW',
    confidence_score: 94,
  },
];
